# Generated by Django 6.1.1 on 2026-09-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_account_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AGRICULTURE", "Agriculture"),
                    ("AUTOMOTIVE", "Automotive"),
                    ("BEAUTY & PERSONAL CARE", "Beauty & Personal Care"),
                    ("CONSTRUCTION", "Construction"),
                    ("EDUCATION", "Education"),
                    ("ENERGY & UTILITIES", "Energy & Utilities"),
                    ("FINANCE & INSURANCE", "Finance & Insurance"),
                    ("FOOD & BEVERAGE", "Food & Beverage"),
                    ("HEALTHCARE", "Healthcare"),
                    ("HOSPITALITY & TOURISM", "Hospitality & Tourism"),
                    ("MANUFACTURING", "Manufacturing"),
                    ("MEDIA & ENTERTAINMENT", "Media & Entertainment"),
                    ("NONPROFIT", "Nonprofit"),
                    ("PROFESSIONAL SERVICES", "Professional Services"),
                    ("REAL ESTATE", "Real Estate"),
                    ("RETAIL & E-COMMERCE", "Retail & E-commerce"),
                    ("HOME & LOCAL SERVICES", "Home & Local Services"),
                    ("TECHNOLOGY", "Technology"),
                    ("TRANSPORTATION & LOGISTICS", "Transportation & Logistics"),
                    ("WHOLESALE & DISTRIBUTION", "Wholesale & Distribution"),
                    ("OTHER", "Other"),
                    ("ADVERTISING", "Advertising"),
                    ("APPAREL & ACCESSORIES", "Apparel & Accessories"),
                    ("BANKING", "Banking"),
                    ("BIOTECHNOLOGY", "Biotechnology"),
                    (
                        "BUILDING MATERIALS & EQUIPMENT",
                        "Building Materials & Equipment",
                    ),
                    ("CHEMICAL", "Chemical"),
                    ("COMPUTER", "Computer"),
                    ("ELECTRONICS", "Electronics"),
                    ("ENERGY", "Energy"),
                    ("ENTERTAINMENT & LEISURE", "Entertainment & Leisure"),
                    ("FINANCE", "Finance"),
                    ("GROCERY", "Grocery"),
                    ("INSURANCE", "Insurance"),
                    ("LEGAL", "Legal"),
                    ("PUBLISHING", "Publishing"),
                    ("SERVICE", "Service"),
                    ("SOFTWARE", "Software"),
                    ("SPORTS", "Sports"),
                    ("TELECOMMUNICATIONS", "Telecommunications"),
                    ("TELEVISION", "Television"),
                    ("TRANSPORTATION", "Transportation"),
                    ("VENTURE CAPITAL", "Venture Capital"),
                ],
                max_length=255,
                null=True,
                verbose_name="Industry",
            ),
        ),
    ]
