# Generated by Django 6.1.1 on 2026-09-29 20:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0067_googleconnection_googlecalendarmirror_and_more"),
        ("contacts", "0022_contact_merge_archive"),
        ("leads", "0016_alter_leadpipeline_is_default"),
        ("webforms", "0002_backfill_legacy_api_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="webform",
            name="contact_source",
            field=models.CharField(
                choices=[
                    ("META", "Meta"),
                    ("GOOGLE", "Google"),
                    ("TIKTOK", "TikTok"),
                    ("ORGANIC", "Organic"),
                    ("CALL", "Call"),
                    ("CUSTOMER_REFERAL", "Customer Referal"),
                    ("EMPLOYER_REFERAL", "Employer Referal"),
                    ("WALK_IN", "Walk In"),
                ],
                default="ORGANIC",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="webform",
            name="notify_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="webform",
            name="notify_in_app",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="webform",
            name="target_model",
            field=models.CharField(
                choices=[("Lead", "Lead"), ("Contact", "Contact")],
                default="Lead",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="webformfield",
            name="external_name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="webformsubmission",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webform_submissions",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="webformsubmission",
            name="email_completed_at",
            # Existing submissions must not resend historical email on rollout.
            field=models.DateTimeField(
                blank=True, null=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="webformsubmission",
            name="email_delivered_to",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="webformsubmission",
            name="request_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="webformfield",
            name="lead_field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("salutation", "Salutation"),
                    ("first_name", "Name"),
                    ("last_name", "Last name"),
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("company_name", "Company name"),
                    ("job_title", "Job title"),
                    ("website", "Website"),
                    ("title", "Job title"),
                    ("description", "Message"),
                    ("city", "City"),
                    ("state", "State / region"),
                    ("country", "Country"),
                    ("postcode", "Postal code"),
                    ("industry", "Industry"),
                    ("organization", "Company"),
                    ("department", "Department"),
                    ("address_line", "Address"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="webformsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("request_id__isnull", False)),
                fields=("form", "request_id"),
                name="webform_unique_request",
            ),
        ),
    ]
