# Generated by Django 6.1.1 on 2026-10-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webforms", "0004_webform_design"),
    ]

    operations = [
        migrations.AddField(
            model_name="webformsubmission",
            name="email_claim_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="webformsubmission",
            name="email_claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
