# Generated by Django 6.1.1 on 2026-09-22 23:21

from django.conf import settings
from django.db import migrations, models


def backfill_phone_keys(apps, schema_editor):
    import re
    Contact = apps.get_model('contacts', 'Contact')
    batch = []
    for contact in Contact.objects.only('id', 'phone').iterator(chunk_size=500):
        digits = re.sub(r'[^0-9]', '', contact.phone or '')
        contact.phone_match_key = digits[2:] if digits.startswith('00') else digits
        batch.append(contact)
        if len(batch) == 500:
            Contact.objects.bulk_update(batch, ['phone_match_key'], batch_size=500)
            batch = []
    if batch:
        Contact.objects.bulk_update(batch, ['phone_match_key'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_required_record_names'),
        ('common', '0062_optional_crm_properties'),
        ('contacts', '0020_optional_record_properties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_match_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First name'),
        ),
        migrations.RunPython(backfill_phone_keys, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['org', 'phone_match_key'], name='contact_org_phone_match_idx'),
        ),
    ]
