# Generated by Django 6.1.1 on 2026-09-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0016_optional_record_properties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
    ]
