export const companyColumns = [
  ['name', 'Name'],
  ['website', 'Domain'],
  ['owner', 'Company Owner'],
  ['industry', 'Industry'],
  ['number_of_employees', 'Number of Employees'],
  ['annual_revenue', 'Annual revenue'],
  ['address_line', 'Address'],
  ['city', 'City'],
  ['state', 'State'],
  ['postcode', 'Zip Code'],
  ['country_display', 'Country'],
  ['pages', 'Pages'],
  ['source_label', 'Source'],
  ['stage_label', 'Stage'],
  ['contacts', 'Contacts'],
  ['created_at', 'Created'],
];
