export const contactColumns = [
  ['name', 'Name'],
  ['phone', 'Phone'],
  ['email', 'Email'],
  ['source_label', 'Source'],
  ['stage_label', 'Stage'],
  ['owner', 'Contact Owner'],
  ['address_line', 'Address'],
  ['city', 'City'],
  ['postcode', 'Zip Code'],
  ['state', 'State'],
  ['language', 'Language'],
  ['preferred_communication_channel_label', 'Preferred Communication Channel'],
  ['description', 'Notes'],
  ['account', 'Company'],
  ['is_active', 'Active'],
  ['do_not_call', 'Do not call'],
  ['created_at', 'Created'],
  ['last_activity_at', 'Last activity'],
  ['updated_at', 'Updated']
];
