# Generated by Django 6.1.1 on 2026-09-16 23:31

from django.db import migrations, models


def protect_relations(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    appointment = apps.get_model('common', 'SalesAppointment')
    for name in ('contacts', 'companies', 'attendee_users'):
        through = appointment._meta.get_field(name).remote_field.through
        table = through._meta.db_table
        schema_editor.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
        schema_editor.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
        schema_editor.execute(f"""CREATE POLICY appointment_org_isolation ON "{table}"
            FOR ALL USING (EXISTS (SELECT 1 FROM sales_appointment a
                WHERE a.id = salesappointment_id AND a.org_id::text = NULLIF(current_setting('app.current_org', true), '')))
            WITH CHECK (EXISTS (SELECT 1 FROM sales_appointment a
                WHERE a.id = salesappointment_id AND a.org_id::text = NULLIF(current_setting('app.current_org', true), '')))""")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_account_communication_channel'),
        ('common', '0047_organization_invitations'),
        ('contacts', '0019_contact_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesappointment',
            name='attendee_users',
            field=models.ManyToManyField(blank=True, related_name='invited_sales_events', to='common.profile'),
        ),
        migrations.AddField(
            model_name='salesappointment',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='attended_sales_events', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='salesappointment',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='attended_sales_events', to='contacts.contact'),
        ),
        migrations.RunPython(protect_relations, migrations.RunPython.noop),
    ]
