# Generated by Django 6.1.1 on 2026-09-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0048_appointment_multiple_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
