# Generated by Django 6.1.1 on 2026-09-17 15:10

from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0049_profile_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_integration_mode",
            field=models.CharField(
                blank=True,
                choices=[("send", "Send only"), ("read_send", "Read and send")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="notify_comments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="notify_in_app",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="notify_mentions",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                validators=[common.validators.validate_iana_timezone],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, upload_to="profile-photos/"),
        ),
    ]
