# Generated by Django 6.1.1 on 2026-09-18 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_roles(apps, schema_editor):
    Org=apps.get_model('common','Org')
    Role=apps.get_model('common','CRMRole')
    Profile=apps.get_model('common','Profile')
    for org in Org.objects.all():
        for name, scope in [('Member','own'),('Manager','team')]:
            rules={module: {'view':scope,'create':True,'edit':scope,'delete':'own','export':scope} for module in ['contacts','companies','deals','tasks','tickets']}
            role=Role.objects.create(org_id=org.pk,name=name,rules=rules)
            if name == 'Member': Profile.objects.filter(org_id=org.pk,role='USER').update(access_role=role)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0050_profile_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('rules', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_roles', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'crm_role',
            },
        ),
        migrations.AddField(
            model_name='organizationinvitation',
            name='access_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='common.crmrole'),
        ),
        migrations.AddField(
            model_name='profile',
            name='access_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='common.crmrole'),
        ),
        migrations.AddConstraint(
            model_name='crmrole',
            constraint=models.UniqueConstraint(fields=('org', 'name'), name='unique_crm_role_name'),
        ),
        migrations.RunPython(seed_roles, migrations.RunPython.noop),
    ]
