# Generated by Django 6.1.1 on 2026-09-18 18:36

from django.db import migrations, models


def set_scopes(apps, schema_editor):
    Org = apps.get_model('common', 'Org')
    Role = apps.get_model('common', 'CRMRole')
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        previous = None
        if connection.vendor == 'postgresql':
            cursor.execute("SELECT current_setting('app.current_org', true)")
            previous = cursor.fetchone()[0]
        try:
            for org in Org.objects.all().iterator():
                if connection.vendor == 'postgresql':
                    cursor.execute("SELECT set_config('app.current_org', %s, true)", [str(org.pk)])
                for role in Role.objects.filter(org_id=org.pk):
                    scopes = {value for row in role.rules.values() for key, value in row.items() if key != 'create' and value in ('own','team','organization')}
                    role.scope = {'Member':'own','Manager':'team'}.get(role.name) or next((scope for scope in ('own','team','organization') if scope in scopes), 'own')
                    # Choose the narrowest existing scope for custom sets; never expand access.
                    role.rules = {module:{action:(value if action == 'create' or value == 'none' else role.scope) for action,value in row.items()} for module,row in role.rules.items()}
                    role.save(update_fields=['scope','rules'])
        finally:
            if connection.vendor == 'postgresql':
                cursor.execute("SELECT set_config('app.current_org', %s, true)", [previous or ''])


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0053_recommended_role_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmrole',
            name='scope',
            field=models.CharField(choices=[('own', 'Personal'), ('team', 'Team'), ('organization', 'Organization')], default='own', max_length=20),
        ),
        migrations.RunPython(set_scopes, migrations.RunPython.noop),
    ]
