# Generated by Django 6.1.1 on 2026-09-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0056_removed_organization_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customfielddefinition",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("textarea", "Textarea"),
                    ("number", "Number"),
                    ("dropdown", "Dropdown"),
                    ("date", "Date"),
                    ("checkbox", "Checkbox"),
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("url", "Link"),
                    ("integer", "Whole number"),
                    ("percentage", "Percentage"),
                    ("money", "Monetary amount"),
                    ("time", "Time"),
                    ("multi_select", "Multiple selection"),
                ],
                max_length=16,
            ),
        ),
    ]
