# Generated by Django 6.1.1 on 2026-09-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0057_additional_property_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='pipeline_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
