# Generated by Django 6.1.1 on 2026-09-29 16:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


def protect_google_tables(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        from common.rls import get_enable_policy_sql

        for table in (
            "google_connection",
            "google_calendar_event",
            "google_mail_activity",
            "google_calendar_mirror",
        ):
            schema_editor.execute(get_enable_policy_sql(table))


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0066_profile_platform_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[("gmail", "Gmail"), ("calendar", "Calendar")],
                        max_length=16,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("encrypted_refresh_token", models.TextField(blank=True)),
                ("scopes", models.JSONField(default=list)),
                ("calendar_id", models.CharField(default="primary", max_length=1024)),
                (
                    "calendar_name",
                    models.CharField(default="Primary calendar", max_length=255),
                ),
                ("calendar_writable", models.BooleanField(default=False)),
                ("history_id", models.CharField(blank=True, max_length=64)),
                ("initial_history_id", models.CharField(blank=True, max_length=64)),
                ("mail_page_token", models.TextField(blank=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(default="disconnected", max_length=20)),
                ("oauth_state_hash", models.CharField(blank=True, max_length=64)),
                ("encrypted_verifier", models.TextField(blank=True)),
                ("oauth_started_at", models.DateTimeField(blank=True, null=True)),
                ("sync_started_at", models.DateTimeField(blank=True, null=True)),
                ("generation", models.UUIDField(default=uuid.uuid4)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.org"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.profile"
                    ),
                ),
            ],
            options={
                "db_table": "google_connection",
            },
        ),
        migrations.CreateModel(
            name="GoogleCalendarMirror",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=1024)),
                ("etag", models.CharField(blank=True, max_length=255)),
                ("fingerprint", models.CharField(blank=True, max_length=64)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.salesappointment",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.org"
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mirrors",
                        to="common.googleconnection",
                    ),
                ),
            ],
            options={
                "db_table": "google_calendar_mirror",
            },
        ),
        migrations.CreateModel(
            name="GoogleCalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=1024)),
                ("title", models.CharField(max_length=1024)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("all_day", models.BooleanField(default=False)),
                ("start_date", models.CharField(blank=True, max_length=10)),
                ("end_date", models.CharField(blank=True, max_length=10)),
                ("href", models.URLField(blank=True, max_length=2048)),
                ("busy", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.org"
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="common.googleconnection",
                    ),
                ),
            ],
            options={
                "db_table": "google_calendar_event",
            },
        ),
        migrations.CreateModel(
            name="GoogleMailActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message_id", models.CharField(max_length=128)),
                ("thread_id", models.CharField(max_length=128)),
                ("contact_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, max_length=1024)),
                ("sender", models.EmailField(max_length=254)),
                ("recipients", models.JSONField(default=list)),
                ("encrypted_body", models.TextField(blank=True)),
                ("direction", models.CharField(max_length=8)),
                ("occurred_at", models.DateTimeField()),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mail_activity",
                        to="common.googleconnection",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.org"
                    ),
                ),
            ],
            options={
                "db_table": "google_mail_activity",
            },
        ),
        migrations.AddConstraint(
            model_name="googleconnection",
            constraint=models.UniqueConstraint(
                fields=("org", "profile", "service"),
                name="google_profile_service_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="googlecalendarmirror",
            constraint=models.UniqueConstraint(
                fields=("connection", "appointment"),
                name="google_mirror_appointment_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="googlecalendarevent",
            index=models.Index(
                fields=["org", "connection", "starts_at"], name="google_events_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="googlecalendarevent",
            constraint=models.UniqueConstraint(
                fields=("connection", "external_id"),
                name="google_calendar_event_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="googlemailactivity",
            index=models.Index(
                fields=["org", "contact_email", "occurred_at"],
                name="google_mail_contact",
            ),
        ),
        migrations.AddConstraint(
            model_name="googlemailactivity",
            constraint=models.UniqueConstraint(
                fields=("connection", "message_id", "contact_email"),
                name="google_mail_activity_unique",
            ),
        ),
        migrations.RunPython(protect_google_tables, migrations.RunPython.noop),
    ]
