# Generated by Django 6.1.1 on 2026-09-30 20:14

import django.db.models.deletion
from django.db import migrations, models


def protect_receipts(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        from common.rls import get_enable_policy_sql

        schema_editor.execute(get_enable_policy_sql("reminder_delivery"))


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0067_googleconnection_googlecalendarmirror_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderDelivery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.org"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.profile"
                    ),
                ),
            ],
            options={
                "db_table": "reminder_delivery",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "recipient", "key"),
                        name="reminder_delivery_once",
                    )
                ],
            },
        ),
        migrations.RunPython(protect_receipts, migrations.RunPython.noop),
    ]
