# Generated by Django 6.1.1 on 2026-10-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0068_reminder_delivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingFileDeletion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "pending_file_deletion",
            },
        ),
    ]
