# Generated by Django 6.1.1 on 2026-10-01 19:06

from django.db import migrations, models

import common.models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0069_pending_file_deletion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachments",
            name="attachment",
            field=models.FileField(
                max_length=1001, upload_to=common.models.attachment_upload_path
            ),
        ),
    ]
