# Generated by Django 6.1.1 on 2026-10-07 17:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0074_google_mail_presentation"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlemailactivity",
            name="reply_to",
            field=models.JSONField(default=list, blank=True),
        ),
        migrations.CreateModel(
            name="GoogleMailSendOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_id", models.UUIDField()),
                ("payload_digest", models.CharField(max_length=64)),
                ("status", models.CharField(default="sending", max_length=16)),
                ("message_id", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.googleconnection",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("connection", "request_id"),
                        name="google_send_request_unique",
                    )
                ],
            },
        ),
    ]
