# Generated by Django 6.1.1 on 2026-09-15 15:42

import django.db.models.deletion
from django.db import migrations, models


def number_existing(apps, schema_editor):
    Case = apps.get_model('cases', 'Case')
    Sequence = apps.get_model('cases', 'TicketSequence')
    for org_id in Case.objects.values_list('org_id', flat=True).distinct():
        count = 0
        for count, pk in enumerate(Case.objects.filter(org_id=org_id).order_by('created_at', 'id').values_list('id', flat=True), 1):
            Case.objects.filter(pk=pk).update(ticket_number=count)
        Sequence.objects.update_or_create(org_id=org_id, defaults={'last_number': count})


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0030_escalationpolicy_first_response_hours_and_more'),
        ('common', '0046_appointment_deal'),
        ('opportunity', '0020_deal_phone_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSequence',
            fields=[
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='common.org')),
                ('last_number', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('Support', 'Support'), ('Billing', 'Billing'), ('Service', 'Service'), ('General', 'General')], default='General', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='opportunity.opportunity'),
        ),
        migrations.AddField(
            model_name='case',
            name='due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='resolution_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='case',
            name='source',
            field=models.CharField(choices=[('Email', 'Email'), ('Call', 'Call'), ('SMS', 'SMS'), ('Website', 'Website'), ('Internal', 'Internal')], default='Internal', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='ticket_number',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='waiting_reason',
            field=models.CharField(blank=True, choices=[('', 'Not set'), ('Customer', 'Customer'), ('Internal', 'Internal')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Assigned', 'In Progress'), ('Pending', 'Waiting'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Rejected', 'Rejected'), ('Duplicate', 'Duplicate')], max_length=64),
        ),
        migrations.AlterField(
            model_name='casestage',
            name='maps_to_status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Assigned', 'In Progress'), ('Pending', 'Waiting'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Rejected', 'Rejected'), ('Duplicate', 'Duplicate')], help_text='When case enters this stage, also update Case.status', max_length=64, null=True, verbose_name='Maps to Status'),
        ),
        migrations.AlterField(
            model_name='reopenpolicy',
            name='reopen_to_status',
            field=models.CharField(choices=[('New', 'New'), ('Assigned', 'In Progress'), ('Pending', 'Waiting'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Rejected', 'Rejected'), ('Duplicate', 'Duplicate')], default='Pending', help_text='Status the case flips to on reopen (must be non-terminal).', max_length=64),
        ),
        migrations.RunPython(number_existing, migrations.RunPython.noop),
    ]
